# _config.yml

title: Deakin Infomation Security Club
email: deakininfosec@gmail.com
repository: DeakinInfoSecClub/DeakinInfoSecClub.github.io
description: >
    A university club for hackers, problem solvers and IT security professionals.
baseurl: ""
url: https://deakininfosec.com.au
timezone: Australia/Melbourne

social:
    facebook: https://facebook.com/groups/DeakinInfoSecClub
    slack: https://discclub.slack.com/
    linkedin: https://www.linkedin.com/company/deakin-information-security-club/
    youtube: https://www.youtube.com/channel/UCilvmmP4dkWJzlxvvTABGNw

calendar:
    embed: https://calendar.google.com/calendar/embed?height=600&amp;wkst=1&amp;bgcolor=%23ffffff&amp;ctz=Australia%2FMelbourne&amp;src=ZjllYnZxaTdrcWp0dDA4dTVoczM5YXFmazhAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ&amp;color=%234285F4&amp;showPrint=0&amp;showTabs=1&amp;showCalendars=0&amp;showTz=0&amp;showDate=0&amp;showTitle=0
    subscribe: https://calendar.google.com/calendar/ical/f9ebvqi7kqjtt08u5hs39aqfk8%40group.calendar.google.com/public/basic.ics

plugins:
    - jekyll-feed
    - jekyll-github-metadata
    - jekyll-redirect-from
    - jekyll-seo-tag
    - jekyll-sitemap
    - jemoji

markdown: kramdown

highlighter: rouge

feed:
    path: atom.xml
    collections:
        - articles
        - cheatsheets
        - sessions
        - workshops

kramdown:
    input: GFM

sass:
    style: compressed

include: ["_pages", "_shortlinks"]
exclude: ["run.sh"]

collections_dir: content
collections:
    articles:
        output: true
        index_path: /kb/articles/
        permalink: /kb/:collection/:title
    cheatsheets:
        output: true
        index_path: /kb/cheatsheets/
        permalink: /kb/:collection/:title
    profiles:
        output: true
        index_path: /kb/profiles/
        permalink: /kb/:collection/:title
    sessions:
        output: true
        index_path: /sessions/
        permalink: /:collection/:title
    workshops:
        output: true
        index_path: /kb/workshops/
        permalink: /kb/:collection/:title

defaults:
    -
        scope:
            path: "_articles"
        values:
            layout: "content"
            type: "article"
            author: "anon"
    -
        scope:
            path: "_cheatsheets"
        values:
            layout: "content"
            type: "cheatsheet"
            author: "anon"
    -
        scope:
            path: "_profiles"
        values:
            layout: "profile"
            type: "profile"
    -
        scope:
            path: "_sessions"
        values:
            layout: "content"
            type: "session"
            author: "The DISC Team"
    -
        scope:
            path: "_workshops"
        values:
            layout: "content"
            type: "workshop"
            author: "anon"